# Generated by Django 3.0.3 on 2020-02-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mystocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myticker', models.CharField(max_length=10)),
                ('myprice', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('myowned', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
