# Generated by Django 3.0.3 on 2020-02-28 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mystocks',
            new_name='Mystockdb',
        ),
    ]
